name = "KernelHom"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["KernelHom"]

[leanOptions]
pp.unicode.fun = true                 # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"

[[require]]
name = "subverso"
git = "https://github.com/leanprover/subverso"

[[lean_lib]]
name = "KernelHom"

[[lean_lib]]
name = "Manual"
srcDir = "verso/"
root = "Manual"

[[lean_exe]]
name = "manual"
srcDir = "verso/"
root = "Manual"
