name = "KernelHom"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["KernelHom"]
testDriver = "KernelHomTests"

[leanOptions]
pp.unicode.fun = true                 # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "KernelHom"

[[lean_lib]]
name = "KernelHomTests"
globs = ["KernelHomTests.+"]

[[lean_lib]]
name = "KernelHomManual"
srcDir = "Verso/"
root = "KernelHomManual"

[[lean_exe]]
name = "manual"
srcDir = "Verso/"
root = "KernelHomManual"
